name: Publish Blog Site

on:
  push:
    branches: [ blog ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
      env:
        GH_PAGES_BRANCH: master
        PELICAN_CONFIG_FILE: publishconf.py
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
