name: Publish Blog Site

on:
  push:
    branches: [ blog ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
      env:
        GH_PAGES_BRANCH: master
        PELICAN_CONFIG_FILE: publishconf.py
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: fjogeleit/http-request-action@master
      with:
        url: 'https://sc.ftqq.com/${{secrets.FTQQ_KEY}}.send?text=%E5%8D%9A%E6%96%87%E5%B7%B2%E5%8F%91%E5%B8%83'
        method: 'GET'
